# 摄像头自动刷新配置

[api]
base_url = "http://183.196.85.67:11016"
# 认证接口
auth_endpoint = "/openapi/mc/v1/authenticate"
# 摄像头列表接口
list_endpoint = "/openapi/usm/v1/camera/list"
# 刷新点位接口
refresh_endpoint = "/openapi/usm/v1/camera/refresh"

[auth]
app_id = "app_id  填写你的app_id"
app_secret = "app_secret 填写你的app_secret"

[refresh]
# 每个点位刷新间隔，单位毫秒（默认 2000ms = 2s）
interval_ms = 2000
# 分页大小
total_count = 20
